POST http://localhost:3333/standup
Content-Type: application/json

{
        "tema": "tema 01",
        "ncapacidade": "286",
        "duracao": "120"
}

###

GET http://localhost:3333/standup 

###

GET http://localhost:3333/standup?search=Standup 

###

PUT http://localhost:3333/standups/ea9da323-aa94-42a1-b9fe-3d50177acd01
Content-Type: application/json

{
    "tema": "Standup",
    "ncapacidade": "286",
    "duracao": "120"
}

###

DELETE http://localhost:3333/standups/c620ed6c-ae3c-45b1-a724-9538269c9a8d
